version: '3'

services:  
  ci-build:
    image: microsoft/aspnetcore-build:1.0-2.0
    container_name: build
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./dotnetcore-compose.sln && dotnet publish ./dotnetcore-compose.sln -c Release -o ./build"